version: '3.8'

services:
  micro_product:
    image: product_app
    container_name: product_app
    ports:
      - "9001:8080"
    networks:
      - backend

networks:
  backend:
    external: true
    name: micro_product_net
